### ISSUE TITLE
Allow a URI instead of a String as configuration parameter

### ISSUE THREAD

**Issue by niko** [amakawa/redic#10]
https://github.com/amakawa/redic/blob/master/lib/redic/client.rb#L21 should check if url is a URI and only try to parse it otherwise.

Right now I'm contructing the URI using URI::Generic.build out of the configuration parameters (as they happen to be a Hash with host, port, db values and I can't change that all over the system). I find it strange that I have to call #to_s on the URI only to have it parsed again.

**Comment by cyx** [comment]
Hi Niko,

That is strange. The main usecase and motivation for doing a URI stems from
12factor.net.

@soveran thoughts?

**Comment by soveran** [comment]
Closing this of inactivity.
